"""pump table

Revision ID: a1fcf4fe8f75
Revises: ede6e1562f96
Create Date: 2018-08-27 15:49:15.001852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1fcf4fe8f75'
down_revision = 'ede6e1562f96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entry_username', table_name='entry')
    op.create_index(op.f('ix_entry_username'), 'entry', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entry_username'), table_name='entry')
    op.create_index('ix_entry_username', 'entry', ['username'], unique=1)
    # ### end Alembic commands ###
