"""pump table

Revision ID: b38e1f85872e
Revises: a1fcf4fe8f75
Create Date: 2018-08-27 16:30:53.230188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b38e1f85872e'
down_revision = 'a1fcf4fe8f75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('concentration', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'concentration')
    # ### end Alembic commands ###
