"""pump table

Revision ID: c5b363ae05c7
Revises: 
Create Date: 2018-08-27 15:28:26.273593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5b363ae05c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('letter', sa.String(length=2), nullable=True),
    sa.Column('level', sa.String(length=10), nullable=True),
    sa.Column('perc', sa.Integer(), nullable=True),
    sa.Column('drug', sa.String(length=90), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('vtbi', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('warning', sa.String(length=200), nullable=True),
    sa.Column('duration', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_timestamp'), 'entry', ['timestamp'], unique=False)
    op.create_index(op.f('ix_entry_username'), 'entry', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entry_username'), table_name='entry')
    op.drop_index(op.f('ix_entry_timestamp'), table_name='entry')
    op.drop_table('entry')
    # ### end Alembic commands ###
